[project]
name = "positive-tool"
version = "0.2.0"
description = "`positive_tool` 一個輔助開發的 Python 工具函式庫。目標提供小而實用的工具"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pytest>=9.0.2"]


[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
log_cli_level = "INFO"
